services:
  db:
    image: postgres:16-alpine
    container_name: mcb-db
    environment:
      POSTGRES_DB: bankdb
      POSTGRES_USER: bank
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U bank -d bankdb"]
      interval: 5s
      timeout: 3s
      retries: 5

volumes:
  pgdata:
