server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:bankdb}
    username: ${DB_USER:bank}
    password: ${DB_PASSWORD:secret}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        jdbc.time_zone: UTC
  flyway:
    enabled: true
    locations: classpath:db/migration

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
  paths-to-match: /api/**         # solo documenta rutas de la API
  override-with-generic-response: false  # ← evita el 500 con ControllerAdvice
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  cache:
    disabled: true

logging:
  level:
    org.springdoc: DEBUG
    com.sergiom.minicorebank: INFO
